/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test void appHasAGreeting() {
        assertEquals(Sum.sum(1, 2), 3);
    }
}
