/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class App {
    public static void main(String[] args) {

        System.out.println(Sum.sum(1, 2));
    }
}
