name: Java CI

on:
  - push
  - pull_request
jobs:
  build:    #Произвольно выбранное название
    runs-on: ubuntu-latest    # Операционная система для работы workflow
    steps:  #Список шагов, которые нужно выполнить
      # action - выполняет какую либо задачу
      # checkout - клонирует репозиторий из $GITHUB_WORKSPACE
      - uses: actions/checkout@v4.0.0
      # run - произвольная bash команда
      - run: ls -la
      - run: echo "${{ github.repository }}"